service: TestProject
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: status
          method: get

plugins:
  - serverless-offline